"""Added first_tim column to EventAttendance

Revision ID: 2b435e4b2bbe
Revises: dbd061b5d50a
Create Date: 2024-11-27 00:52:46.529693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database import Base


# revision identifiers, used by Alembic.
revision: str = '2b435e4b2bbe'
down_revision: Union[str, None] = 'dbd061b5d50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attandance', sa.Column('first_time', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_attandance', 'first_time')
    # ### end Alembic commands ###
